#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------
version: '3'
services:
  vscode-remote:
    image: fatindeed/vscode-remote-php
    environment:
      TIMEZONE: Asia/Shanghai
    volumes:
    # Update this to wherever you want VS Code to mount the folder of your project
    - ..:/workspace
    # This lets you avoid setting up Git again in the container
    - $USERPROFILE/vscode-remote:/home/vscode
    # Forwarding the socket is optional, but lets docker work inside the container if you install the Docker CLI.
    # See the docker-in-docker-compose definition for details on how to install it.
    # - /var/run/docker.sock:/var/run/docker.sock
    - profile:/root/.vscode-remote
volumes:
  profile: